# Generated by Django 4.2 on 2023-04-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_comment_created_date_alter_comment_user'),
        ('main_app', '0003_alter_post_city_alter_post_name'),
    ]

    operations = [
    ]
